// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	calories "daily-tracker-calories/bussiness/calories"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetCalorieByUserID provides a mock function with given fields: id
func (_m *Repository) GetCalorieByUserID(id int) (*calories.Domain, error) {
	ret := _m.Called(id)

	var r0 *calories.Domain
	if rf, ok := ret.Get(0).(func(int) *calories.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*calories.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCalorieFloat provides a mock function with given fields: id
func (_m *Repository) GetCalorieFloat(id int) (float64, error) {
	ret := _m.Called(id)

	var r0 float64
	if rf, ok := ret.Get(0).(func(int) float64); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(float64)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: calorie, idUser
func (_m *Repository) Insert(calorie *calories.Domain, idUser int) (*calories.Domain, error) {
	ret := _m.Called(calorie, idUser)

	var r0 *calories.Domain
	if rf, ok := ret.Get(0).(func(*calories.Domain, int) *calories.Domain); ok {
		r0 = rf(calorie, idUser)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*calories.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*calories.Domain, int) error); ok {
		r1 = rf(calorie, idUser)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: calorie, id
func (_m *Repository) Update(calorie *calories.Domain, id int) (*calories.Domain, error) {
	ret := _m.Called(calorie, id)

	var r0 *calories.Domain
	if rf, ok := ret.Get(0).(func(*calories.Domain, int) *calories.Domain); ok {
		r0 = rf(calorie, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*calories.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*calories.Domain, int) error); ok {
		r1 = rf(calorie, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
