// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	foodAPI "daily-tracker-calories/bussiness/foodAPI"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetFoodByName provides a mock function with given fields: name
func (_m *Repository) GetFoodByName(name string) (*foodAPI.Domain, error) {
	ret := _m.Called(name)

	var r0 *foodAPI.Domain
	if rf, ok := ret.Get(0).(func(string) *foodAPI.Domain); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*foodAPI.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
