// Code generated by mockery v2.9.4. DO NOT EDIT.

package mocks

import (
	foods "daily-tracker-calories/bussiness/foods"

	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// DeleteFood provides a mock function with given fields: id, food
func (_m *Service) DeleteFood(id int, food *foods.Domain) (*foods.Domain, error) {
	ret := _m.Called(id, food)

	var r0 *foods.Domain
	if rf, ok := ret.Get(0).(func(int, *foods.Domain) *foods.Domain); ok {
		r0 = rf(id, food)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*foods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *foods.Domain) error); ok {
		r1 = rf(id, food)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// EditFood provides a mock function with given fields: id, food
func (_m *Service) EditFood(id int, food *foods.Domain) (*foods.Domain, error) {
	ret := _m.Called(id, food)

	var r0 *foods.Domain
	if rf, ok := ret.Get(0).(func(int, *foods.Domain) *foods.Domain); ok {
		r0 = rf(id, food)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*foods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, *foods.Domain) error); ok {
		r1 = rf(id, food)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllFood provides a mock function with given fields:
func (_m *Service) GetAllFood() (*[]foods.Domain, error) {
	ret := _m.Called()

	var r0 *[]foods.Domain
	if rf, ok := ret.Get(0).(func() *[]foods.Domain); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]foods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFoodAPI provides a mock function with given fields: name
func (_m *Service) GetFoodAPI(name string) (*foods.Domain, error) {
	ret := _m.Called(name)

	var r0 *foods.Domain
	if rf, ok := ret.Get(0).(func(string) *foods.Domain); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*foods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFoodByID provides a mock function with given fields: id
func (_m *Service) GetFoodByID(id int) (*foods.Domain, error) {
	ret := _m.Called(id)

	var r0 *foods.Domain
	if rf, ok := ret.Get(0).(func(int) *foods.Domain); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*foods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFoodByName provides a mock function with given fields: name
func (_m *Service) GetFoodByName(name string) (*foods.Domain, error) {
	ret := _m.Called(name)

	var r0 *foods.Domain
	if rf, ok := ret.Get(0).(func(string) *foods.Domain); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*foods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveFood provides a mock function with given fields: food
func (_m *Service) SaveFood(food *foods.Domain) (*foods.Domain, error) {
	ret := _m.Called(food)

	var r0 *foods.Domain
	if rf, ok := ret.Get(0).(func(*foods.Domain) *foods.Domain); ok {
		r0 = rf(food)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*foods.Domain)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*foods.Domain) error); ok {
		r1 = rf(food)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
